<a href="https://colab.research.google.com/github/dnaneet/ComputationalMechanicsPlayGround/blob/master/Kattan_2x1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Python program solves problem 2.1 in Peter Kattan's book *MATLAB Guide to Finite Elements An Interactive Approach*.

Calculate the deflections at nodes 2 and 3 when P=15 (choose your own units).
![Kattan 2.1](https://raw.githubusercontent.com/dnaneet/ComputationalMechanicsPlayGround/master/Kattan_2x1.png)

In [0]:
import numpy as np

In [0]:
'''
The following functions are defined:

SpringElementStiffness(): Assemble local
stiffness matrix.  
Args: stiffness value

SpringAssemble(): Assemble local stiffness
matrices to create a global stiffness matrix
Args: Global stiffness matrix, local stiffness matrix 
and nodal connectivity
'''

def SpringElementStiffness(k):
  y = np.array([[k, -k],[-k, k]])
  return y

def SpringAssemble(K, k, i, j):
  K[i,i] = K[i,i] + k[0,0]
  K[i,j] = K[i,j] + k[0,1]
  K[j,i] = K[j,i] + k[1,0]
  K[j,j] = K[j,j] + k[1,1]
  return K


In [3]:
'''
This is the initialization cell.
All initial values are defined
or calculated in this cell.
'''
nNodes=3
k1 = SpringElementStiffness(100)
k2 = SpringElementStiffness(200)
k3 = k2
K = np.zeros((nNodes, nNodes))
K = SpringAssemble(K, k1, 0,1)
K = SpringAssemble(K, k2, 1,2)
print(K)

[[ 100. -100.    0.]
 [-100.  300. -200.]
 [   0. -200.  200.]]


In [4]:
'''
boundary condition application:
Set rows and columns corresponding
to boundary condition notes to zero.
Remove all zero elements and reshape matrix
to nNodes - nBC

The operations performed here use vectorization
and avoid for loops and while statements
'''
bcs = [0]
nBC = len(bcs);
K[0,:] = 0
K[:,0] = 0
K = K[K!=0].reshape(nNodes-nBC, nNodes-nBC) #global stiffness matrix
                                            #arrived at by omitting
                                            #all rows and columns that 
                                            #have "0" (fixed nodes)
print(K)                                            

[[ 300. -200.]
 [-200.  200.]]


In [5]:
'''
Matrix inversion to calculate
deflection, given the force.
'''
f = np.array([0,15])
np.linalg.solve(K,f)

array([0.15 , 0.225])